---
  - src: https://github.com/AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.11.1"
    name: clickhouse
  - src: https://github.com/Dimi-link/vector-role.git
    scm: git
    version: vector-role
    name: vector-role
  - src: https://github.com/Dimi-link/lighthouse-role.git
    scm: git
    version: lighthouse-role
    name: lighthouse-role